### ISSUE TITLE
能否添加gemeni的API代理

### ISSUE THREAD

**Issue by ccoc-cc** [wenyikun/deno-proxy#1]
google 最新的gemeni Pro的API也出来了，要是支持就更好了。感谢

**Comment by wenyikun** [comment]
> google 最新的gemeni Pro的API也出来了，要是支持就更好了。感谢
![WX20240120-032153@2x](https://github.com/wenyikun/deno-proxy/assets/24750200/24db3dc5-14ab-404c-bcfd-6e9291be2afa)
Fork一下，把地址改成gemeni的就行 https://generativelanguage.googleapis.com

**Comment by wenyikun** [comment]
> google 最新的gemeni Pro的API也出来了，要是支持就更好了。感谢

![WX20240120-032153@2x](https://github.com/wenyikun/deno-proxy/assets/24750200/b054f012-36be-4ea9-8c16-9533dd2f3dff)
Fork一下，把地址改成gemeni的就行 https://generativelanguage.googleapis.com
